# Generated by Django 3.2.5 on 2024-07-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_auto_20201124_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='clas',
            field=models.CharField(choices=[('P1', 'PRIMARY ONE'), ('P2', 'PRIMARY TWO'), ('P3', 'PRIMARY THREE'), ('P4', 'PRIMARY FOUR'), ('P5', 'PRIMARY FIVE'), ('P6', 'PRIMARY SIX'), ('P7', 'PRIMARY SEVEN')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
